#!/usr/bin/with-contenv bash

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

cd /app/deepstack/server || exit

echo "Starting Deepstack."
exec s6-setuidgid abc \
	./server
